### ISSUE TITLE
Where is the npm package?

### ISSUE THREAD

**Issue by johnnyasantoss** [pc035860/ngQueue#4]
Hello you might noticed that bower was [deprecated][bower], thus you probably should upload this in `npm` for easing the package download :)
The company I'm working for is using this package and we're migrating away from bower.

I appreciate your work making this awesome lib :1st_place_medal: 

 [bower]: https://github.com/bower/bower/issues/2298#issuecomment-302792690

**Comment by pc035860** [comment]
I'll find some time to wrapped it into UMD (unlikely to go ES6 module for now) and publish it on npm.
Please wait for my good news.

**Comment by pc035860** [comment]
@johnnyasantoss I just published it on npm. Please let me know if it does work for you. Thanks.

https://www.npmjs.com/package/ng-queue
